name: End-to-end tests
on: [push]
jobs:
  cypress-run-e2e:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        usus: action/checkout@v2

      - name: Cypress run
        usus: cypress-io/github-action@v4
        with:
          command: npm run test-e2e